server:
  port: 8080
spring:
  datasource:
    data-username: root
    data-password: root
    url: jdbc:mysql://localhost:3306/1908t?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
